In [2]:
from datasets import load_dataset
import pandas as pd

# SST-5 (default = 5 klas)
dataset = load_dataset("sst", "default")

/home/julita/anaconda3/envs/anote/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:

train_dataset = dataset['train'].to_pandas()

In [4]:
print(train_dataset['label'].value_counts())

label
0.77778    236
0.72222    226
0.27778    220
0.50000    207
0.22222    207
          ...
0.95833     17
0.00000     16
0.97222     13
0.98611     11
0.63194      1
Name: count, Length: 74, dtype: int64

In [5]:
train_dataset

,sentence,label,tokens,tree
0,The Rock is destined to be the 21st Century 's...,0.69444,The|Rock|is|destined|to|be|the|21st|Century|'s...,70|70|68|67|63|62|61|60|58|58|57|56|56|64|65|5...
1,The gorgeously elaborate continuation of `` Th...,0.83333,The|gorgeously|elaborate|continuation|of|``|Th...,71|70|69|69|67|67|66|64|63|62|62|61|61|58|57|5...
2,Singer\/composer Bryan Adams contributes a sle...,0.62500,Singer\/composer|Bryan|Adams|contributes|a|sle...,72|71|71|70|68|68|67|67|66|63|62|62|60|60|58|5...
3,You 'd think by now America would have had eno...,0.50000,You|'d|think|by|now|America|would|have|had|eno...,36|35|34|33|33|32|30|29|27|26|25|24|23|23|22|2...
4,Yet the act is still charming here .,0.72222,Yet|the|act|is|still|charming|here|.,15|13|13|10|9|9|11|12|10|11|12|14|14|15|0
...,...,...,...,...
8539,A real snooze .,0.11111,A|real|snooze|.,7|6|5|5|6|7|0
8540,No surprises .,0.22222,No|surprises|.,5|4|4|5|0
8541,We 've seen the hippie-turned-yuppie plot befo...,0.75000,We|'ve|seen|the|hippie-turned-yuppie|plot|befo...,41|40|38|37|36|36|39|42|43|35|34|31|30|30|29|2...
8542,Her fans walked out muttering words like `` ho...,0.13889,Her|fans|walked|out|muttering|words|like|``|ho...,62|62|55|55|53|53|52|51|50|49|48|47|47|57|58|5...
8543,In this case zero .,0.34722,In|this|case|zero|.,8|8|7|6|6|7|9|9|0

In [6]:

train_dataset['label_binned'] = pd.cut(train_dataset['label'], bins=5, labels=[1, 2,3 , 4, 5])
print(train_dataset['label_binned'].value_counts())

label_binned
4    2322
2    2218
3    1624
5    1288
1    1092
Name: count, dtype: int64

In [7]:
train_dataset['label_binned'].value_counts()

label_binned
4    2322
2    2218
3    1624
5    1288
1    1092
Name: count, dtype: int64

In [8]:
train_subset = train_dataset.groupby('label_binned').apply(lambda x: x.sample(200, random_state=42)).reset_index(drop=True)
train_subset = train_subset.sample(frac=1, random_state=42)

/tmp/ipykernel_89209/1062221072.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  train_subset = train_dataset.groupby('label_binned').apply(lambda x: x.sample(200, random_state=42)).reset_index(drop=True)
/tmp/ipykernel_89209/1062221072.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_subset = train_dataset.groupby('label_binned').apply(lambda x: x.sample(200, random_state=42)).reset_index(drop=True)

In [9]:
train_subset

,sentence,label,tokens,tree,label_binned
521,Though the opera itself takes place mostly ind...,0.402780,Though|the|opera|itself|takes|place|mostly|ind...,46|43|43|42|42|40|40|41|39|38|36|35|34|33|32|3...,3
737,If you can read the subtitles ( the opera is s...,0.694440,If|you|can|read|the|subtitles|(|the|opera|is|s...,58|57|53|52|51|51|50|47|47|46|45|44|44|49|55|4...,4
740,( `` Safe Conduct '' ) is a long movie at 163 ...,0.722220,(|``|Safe|Conduct|''|)|is|a|long|movie|at|163|...,63|62|59|59|60|61|58|56|55|55|54|53|53|65|52|5...,4
660,The beauty of Alexander Payne 's ode to the Ev...,0.611110,The|beauty|of|Alexander|Payne|'s|ode|to|the|Ev...,27|27|26|23|22|22|24|21|20|20|18|17|16|16|19|1...,4
411,The fourth in a series that I 'll bet most par...,0.541670,The|fourth|in|a|series|that|I|'ll|bet|most|par...,27|27|26|25|25|24|23|22|21|19|19|18|18|30|17|1...,3
...,...,...,...,...,...
106,"In other words , it 's badder than bad .",0.083333,"In|other|words|,|it|'s|badder|than|bad|.",18|17|17|16|15|13|12|11|11|14|12|13|14|15|16|1...,1
270,The direction occasionally rises to the level ...,0.277780,The|direction|occasionally|rises|to|the|level|...,52|52|51|50|49|47|47|46|45|45|54|55|43|42|41|4...,2
860,The movie is ingenious fun .,0.833330,The|movie|is|ingenious|fun|.,10|10|8|7|7|9|8|9|11|11|0,5
435,The cast comes through even when the movie doe...,0.569440,The|cast|comes|through|even|when|the|movie|doe...,20|20|18|17|15|15|13|13|12|12|19|14|14|16|16|1...,3
102,Most of the movie is so deadly dull that watch...,0.097222,Most|of|the|movie|is|so|deadly|dull|that|watch...,38|37|36|36|33|31|31|32|30|28|26|25|25|27|24|2...,1

In [10]:
train_subset = train_subset[['sentence', 'label_binned']]
train_subset.columns = ['text', 'label']
train_subset

                                                  text label
521  Though the opera itself takes place mostly ind...     3
737  If you can read the subtitles ( the opera is s...     4
740  ( `` Safe Conduct '' ) is a long movie at 163 ...     4
660  The beauty of Alexander Payne 's ode to the Ev...     4
411  The fourth in a series that I 'll bet most par...     3
..                                                 ...   ...
106           In other words , it 's badder than bad .     1
270  The direction occasionally rises to the level ...     2
860                       The movie is ingenious fun .     5
435  The cast comes through even when the movie doe...     3
102  Most of the movie is so deadly dull that watch...     1

[1000 rows x 2 columns]

In [11]:
train_subset.to_csv('train_subset.csv', index=False)